export const demoResponses = {
  generateRequirements: {
    functionalRequirements: [
      { title: 'User Authentication & Role Management', description: 'The system shall provide secure authentication for students, supervisors, and administrators with role-based access control. Users must log in using email and password, and the system shall distinguish between student, supervisor, and admin roles.', priority: 'high' },
      { title: 'Project Workspace Creation', description: 'Students shall be able to create a project workspace by providing a title, description, category, department, and academic year. The creator shall automatically become the project leader.', priority: 'high' },
      { title: 'AI-Powered Requirements Generation', description: 'The system shall allow users to input a vague project description and receive structured functional and non-functional requirements generated by AI, complete with ambiguity warnings for vague terms.', priority: 'high' },
      { title: 'Task Assignment & Evidence Tracking', description: 'Team leaders and supervisors shall assign tasks to members with priority levels and deadlines. Members shall upload screenshots, documents, or code as evidence upon task completion.', priority: 'medium' },
      { title: 'Peer Review Submission', description: 'Team members shall submit peer reviews for each other across five dimensions: reliability, technical contribution, communication, meeting attendance, and documentation contribution.', priority: 'medium' },
      { title: 'Viva Practice & AI Evaluation', description: 'The system shall generate examiner-style defense questions based on project context and allow students to submit practice answers. AI shall evaluate answers for clarity, correctness, depth, and confidence.', priority: 'high' },
    ],
    nonFunctionalRequirements: [
      { title: 'Page Load Performance', category: 'performance', description: '[Category: performance] The application shall load initial page content within 2 seconds under normal network conditions (measured from navigation start to first contentful paint) for at least 90% of page requests.', priority: 'high' },
      { title: 'Concurrent User Support', category: 'performance', description: '[Category: performance] The platform shall support at least 50 concurrent users during peak usage periods without degrading response time beyond 3 seconds for API requests.', priority: 'medium' },
      { title: 'Data Encryption at Rest', category: 'security', description: '[Category: security] All user passwords shall be hashed using bcrypt with a minimum cost factor of 10. All personally identifiable information stored in the database shall be protected through encryption at rest.', priority: 'high' },
      { title: 'Session Security', category: 'security', description: '[Category: security] JWT tokens shall expire after 7 days. The system shall invalidate tokens on logout and reject requests with expired or malformed tokens with a 401 response.', priority: 'high' },
      { title: 'Cross-Browser Compatibility', category: 'usability', description: '[Category: usability] The web application shall render correctly and function fully on the latest two major versions of Chrome, Firefox, Safari, and Edge browsers.', priority: 'medium' },
    ],
    ambiguityWarnings: [
      { vagueTerm: 'secure', explanation: 'The term "secure" is subjective and lacks measurable criteria. Security means different things in different contexts — authentication, encryption, access control, or audit logging.', suggestion: 'Replace with specific security mechanisms such as "bcrypt password hashing", "JWT token authentication", or "role-based access control".' },
      { vagueTerm: 'fast', explanation: '"Fast" is a relative term without a quantified threshold. What feels fast to one user may be unacceptable to another.', suggestion: 'Specify exact response time targets, e.g., "page load within 2 seconds" or "API response under 500ms".' },
      { vagueTerm: 'user-friendly', explanation: '"User-friendly" is highly subjective and cannot be objectively measured or tested without specific usability criteria.', suggestion: 'Define concrete usability requirements such as "complete onboarding in under 3 steps" or "achieve task completion rate above 90% in usability testing".' },
    ],
  },

  generateAcceptanceCriteria: {
    criteria: [
      'Given a registered user, when they enter their email and correct password, then the system shall redirect them to the dashboard within 2 seconds.',
      'Given a registered user, when they enter an incorrect password, then the system shall display an error message "Invalid email or password" and not reveal which field is incorrect.',
      'Given an unauthenticated user, when they try to access a protected route like /dashboard, then the system shall redirect them to the login page.',
      'Given an authenticated user, when they visit any page, then the sidebar shall display their name, role, and profile avatar.',
      'Given a student user, when they view the sidebar, then they shall see links to: Dashboard, Projects, Profile, and Viva Practice.',
      'Given a supervisor user, when they view the sidebar, then they shall see links to: Dashboard, Supervised Projects, and Profile.',
    ],
  },

  generateTestCases: {
    testCases: [
      { testTitle: 'Successful login with valid credentials', testSteps: '1. Navigate to /login\n2. Enter valid email address\n3. Enter valid password\n4. Click "Sign In" button', expectedResult: 'User is redirected to /dashboard. JWT token is stored in localStorage. Sidebar shows user name and role.' },
      { testTitle: 'Login failure with invalid password', testSteps: '1. Navigate to /login\n2. Enter valid email address\n3. Enter incorrect password\n4. Click "Sign In" button', expectedResult: 'Error toast appears: "Invalid credentials". No token is stored. User remains on /login.' },
      { testTitle: 'Redirect unauthenticated access to protected route', testSteps: '1. Clear localStorage\n2. Navigate directly to /dashboard\n3. Observe redirect behavior', expectedResult: 'User is redirected to /login with no error flash.' },
    ],
  },

  refineRequirement: {
    refinedTitle: 'User Login with Role-Based Access Control',
    refinedDescription: 'The system shall authenticate users via email and password using bcrypt hashing. Upon successful authentication, the system shall issue a JWT token with a 7-day expiry containing the user ID, email, and role (student, supervisor, or admin). The system shall use this token to enforce role-based access control on all protected API routes, returning 401 for missing tokens and 403 for insufficient permissions.',
    suggestedPriority: 'high',
    changes: 'Added specific authentication mechanism (bcrypt), token specification (JWT with 7-day expiry and payload claims), and explicit error handling (401/403 responses). Removed vague terms "securely" and "easily".',
  },

  resolveAmbiguity: {
    resolvedDescription: 'The platform homepage shall achieve a First Contentful Paint (FCP) of under 2 seconds and a Largest Contentful Paint (LCP) of under 3 seconds when tested on a simulated 4G network connection (50 Mbps down, 10 Mbps up, 40ms latency) using the Chrome Lighthouse audit tool. The page weight shall not exceed 500KB of uncompressed JavaScript and CSS resources.',
    improvements: [
      'Replaced "load really fast" with specific FCP and LCP targets under defined network conditions',
      'Replaced "under stress" with specific performance benchmark (Lighthouse audit on simulated 4G)',
      'Added measurable page weight budget constraint of 500KB',
    ],
  },

  generateVivaQuestions: {
    questions: [
      { category: 'requirements', difficulty: 'basic', questionText: 'Can you walk us through the process your team used to gather and refine the requirements for this project? Which requirements changed the most from your initial proposal, and why?', suggestedAnswer: 'The team conducted stakeholder interviews and used the platform\'s AI-assisted requirements tool to refine vague ideas into testable specifications. The authentication module saw the most changes because initial assumptions about role hierarchy were too simplistic.' },
      { category: 'architecture', difficulty: 'intermediate', questionText: 'Your architecture uses React on the frontend and Express on the backend. Walk us through a complete data flow — from the user clicking a button to data being persisted and back.', suggestedAnswer: 'The data flow is unidirectional: React component dispatches an Axios call to Express API → Express controller validates with Zod → Prisma ORM translates to PostgreSQL query → response flows back through the same chain. The Vite dev server proxies /api calls to Express on port 5000 so there are no CORS issues in development.' },
      { category: 'database', difficulty: 'advanced', questionText: 'The schema uses composite unique constraints on peer reviews and team members. Explain why you chose these constraints and how they prevent data corruption. What would happen if these constraints were missing?', suggestedAnswer: 'The composite unique on projectId+reviewerId+reviewedUserId ensures one review per reviewer per team member, preventing duplicate submissions that could unfairly weight contribution scores. Without it, a malicious or careless reviewer could submit multiple ratings, skewing the peer review average.' },
      { category: 'testing', difficulty: 'basic', questionText: 'How did you test the contribution scoring algorithm? What test cases did you write to verify that the weighted calculations are correct?', suggestedAnswer: 'We used unit tests with known inputs: tasks (30%), evidence (20%), logs (15%), peer reviews (15%), deadlines (10%), supervisor (10%). Test cases included edge cases like zero tasks, no evidence uploaded, and maximum peer review scores. Each sub-score is calculated independently before the weighted composite.' },
      { category: 'security', difficulty: 'intermediate', questionText: 'What security measures does your system have in place to protect student data and prevent unauthorized access to project workspaces?', suggestedAnswer: 'Three tiers: JWT authentication verifying tokens on every request, role-based authorization middleware checking permissions, and project access middleware ensuring users only access their own projects. Additional measures: bcrypt password hashing (cost factor 10), Helmet HTTP headers, CORS whitelisting, and rate limiting on auth endpoints.' },
      { category: 'contribution', difficulty: 'brutal', questionText: 'Your contribution algorithm gives a default supervisor score of 85 if no supervisor feedback exists. Defend this design decision. How does this not artificially inflate the contributions of unsupervised students?', suggestedAnswer: 'The 85-point default is a deliberate conservative baseline that assumes average performance in the absence of supervisory input. It prevents the system from penalizing students whose supervisors are not actively using the platform. The alternative — defaulting to 0 — would unfairly punish teams for factors outside their control. The score can only decrease if imbalance warnings are detected.' },
      { category: 'originality', difficulty: 'advanced', questionText: 'Beyond the requirement of building a capstone project, what genuinely novel contribution does your system make to the problem of student project supervision?', suggestedAnswer: 'The key novelty is the integration of AI ambiguity detection with contribution analytics in a single supervised workspace. Existing tools handle requirements engineering or project management, but none connect vague requirement detection, peer-reviewed contribution scoring, and viva readiness assessment into one cohesive pipeline tailored for academic supervision.' },
      { category: 'future_work', difficulty: 'intermediate', questionText: 'If you had another semester to improve this system, what would be the three most impactful features you would add, and how would you prioritize them?', suggestedAnswer: '1. Real-time collaboration (WebSockets for live editing requirements) — highest impact for team usability. 2. Plagiarism detection for uploaded code and documents — important for academic integrity. 3. Automated supervisor notifications via email/Slack when projects fall below readiness thresholds — improves supervisor engagement.' },
    ],
  },

  evaluateVivaAnswer: {
    score: 78,
    clarity: 'strong',
    correctness: 'accurate',
    technicalDepth: 'superficial',
    confidence: 'confident',
    feedback: 'Your answer demonstrates a solid grasp of the standard architecture pattern, but you fall short of explaining why React and Express were chosen over alternatives. The examiner would expect you to justify technology choices (e.g., React for component reusability vs. Vue or Svelte, Express for middleware ecosystem vs. Fastify or Hono). Also, mention how the Vite proxy configuration affects development vs. production data flow. Review the trade-offs between SPA architecture and server-rendered alternatives.',
  },

  analyzeFiles: {
    summary: 'The uploaded files indicate a well-structured project with clear documentation and organized code.',
    strengths: [
      'Comprehensive README with setup instructions and project overview',
      'Well-organized codebase with clear separation of concerns',
      'Documentation includes API endpoint descriptions',
      'Code follows consistent naming conventions',
    ],
    improvements: [
      'Add inline code comments for complex business logic',
      'Consider adding a contribution guide for new team members',
      'Include environment variable documentation in a .env.example file',
    ],
    risks: [
      'No test coverage detected in submitted files',
      'Missing security audit documentation',
    ],
    recommendedFileTypes: ['proposal', 'report', 'slides'],
  },
};

export const simulateDemoDelay = () => new Promise((resolve) => setTimeout(resolve, 800 + Math.random() * 700));
