import React, { useState } from 'react';
import { Search, ChevronDown, HelpCircle, X } from 'lucide-react';
import { useOnboarding } from '../context/OnboardingContext';
import '../styles/help-center.css';

const helpSections = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: '🚀',
    items: [
      {
        q: 'How do I create a new project?',
        a: 'Click "New project" on the Studio Board. Enter a project name, description, and select your team members. You can invite supervisors to provide feedback.',
      },
      {
        q: 'How do I invite team members?',
        a: 'Go to your project workspace and click "Team" in the left sidebar. Click "Add team member" and enter their email. They\'ll receive an invitation to join.',
      },
      {
        q: 'What roles are available?',
        a: 'Student (creates and manages project), Supervisor (reviews and provides feedback), Admin (manages all projects). You can have multiple supervisors per project.',
      },
    ],
  },
  {
    id: 'requirements',
    title: 'Requirements & Analysis',
    icon: '📋',
    items: [
      {
        q: 'How do I use AI to generate requirements?',
        a: 'On the Requirements tab, paste your project idea and click "Generate with AI". The system will create structured requirements, acceptance criteria, and test cases.',
      },
      {
        q: 'Can I edit AI-generated requirements?',
        a: 'Yes! All requirements are fully editable. Click the edit button next to any requirement to modify it. You can also add your own requirements manually.',
      },
      {
        q: 'What is acceptance criteria?',
        a: 'Acceptance criteria define when a requirement is considered complete. They\'re specific, testable conditions that must be met before marking a task as done.',
      },
    ],
  },
  {
    id: 'tasks',
    title: 'Tasks & Evidence',
    icon: '✅',
    items: [
      {
        q: 'How do I create a task?',
        a: 'Go to Tasks and click "Create task". Link it to a requirement, add a description, assign it to a team member, and set a deadline.',
      },
      {
        q: 'What counts as evidence?',
        a: 'Evidence is any file that proves work was completed: source code, screenshots, test results, design files, documentation, or presentations.',
      },
      {
        q: 'How do I upload evidence?',
        a: 'On any task, click "Add evidence" and select a file. You can upload multiple files per task. Add a description to explain what the evidence shows.',
      },
      {
        q: 'What are task statuses?',
        a: 'Open (not started), In progress (actively working), In review (waiting for feedback), Closed (complete), Needs changes (revision required).',
      },
    ],
  },
  {
    id: 'documents',
    title: 'Documents & Analysis',
    icon: '📄',
    items: [
      {
        q: 'What types of documents can I upload?',
        a: 'Proposals, reports, presentations, source code archives, design documents, test reports, or any other project evidence.',
      },
      {
        q: 'How does AI document analysis work?',
        a: 'Upload your documents and click "Run review". AI reads them and surfaces gaps, missing content, and next steps to move your project forward.',
      },
      {
        q: 'Can I connect a GitHub repository?',
        a: 'Yes! Go to settings and click "Connect Repository". Install the GitHub app and CapstoneGuard will automatically import documentation files from your repo.',
      },
      {
        q: 'What files are imported from GitHub?',
        a: 'README files, documentation, architecture guides, design documents, and test reports from the docs/ and other standard documentation folders.',
      },
    ],
  },
  {
    id: 'viva',
    title: 'Viva Practice',
    icon: '🎤',
    items: [
      {
        q: 'What is Viva Practice?',
        a: 'Practice questions generated by AI based on your project. These help you prepare for your presentation and identify areas needing more explanation.',
      },
      {
        q: 'How are questions generated?',
        a: 'AI analyzes your requirements, tasks, and uploaded documents to create realistic questions about your project design, implementation, and decisions.',
      },
      {
        q: 'Can I get feedback on my answers?',
        a: 'Yes! After answering a question, click "Get feedback" and AI will evaluate your response and suggest improvements.',
      },
      {
        q: 'Can I share Viva questions with my team?',
        a: 'Yes, your team members can access the same Viva practice questions in their copy of the project. Use them to prepare together.',
      },
    ],
  },
  {
    id: 'collaboration',
    title: 'Collaboration & Feedback',
    icon: '💬',
    items: [
      {
        q: 'How do I leave comments?',
        a: 'Click the comment icon on any section (project dashboard, requirements, tasks, or documents). Comments help supervisors and team members communicate.',
      },
      {
        q: 'How do supervisors provide feedback?',
        a: 'Supervisors can comment on any part of your project—requirements, evidence, documents. Use their feedback to improve your work.',
      },
      {
        q: 'Can I track contributions?',
        a: 'Yes! The Contributions tab shows who uploaded files and evidence. This helps track effort and demonstrate individual work.',
      },
    ],
  },
  {
    id: 'settings',
    title: 'Project Settings',
    icon: '⚙️',
    items: [
      {
        q: 'How do I change project settings?',
        a: 'Go to Settings in your project workspace. You can update the project name, description, and repository connection.',
      },
      {
        q: 'Can I delete a project?',
        a: 'Yes, but only project creators can delete projects. Go to Settings and click "Delete project". This action cannot be undone.',
      },
      {
        q: 'How do I leave a project?',
        a: 'Click on the project card and select "Leave project". You\'ll no longer have access unless reinvited.',
      },
    ],
  },
];

export const HelpCenter = () => {
  const { showHelp, closeHelp, startTour } = useOnboarding();
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedItems, setExpandedItems] = useState(new Set());

  if (!showHelp) return null;

  const toggleItem = (id) => {
    const newExpanded = new Set(expandedItems);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedItems(newExpanded);
  };

  const filteredSections = helpSections
    .map(section => ({
      ...section,
      items: section.items.filter(
        item =>
          item.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
          item.a.toLowerCase().includes(searchQuery.toLowerCase())
      ),
    }))
    .filter(section => section.items.length > 0);

  return (
    <div className="help-center-overlay" onClick={closeHelp}>
      <div className="help-center-modal" onClick={e => e.stopPropagation()}>
        <div className="help-center-header">
          <div>
            <h2>Help & Support</h2>
            <p>Find answers and learn how to use CapstoneGuard</p>
          </div>
          <button
            className="help-center-close"
            onClick={closeHelp}
            aria-label="Close help"
          >
            <X size={20} />
          </button>
        </div>

        <div className="help-center-search">
          <Search size={18} />
          <input
            type="text"
            placeholder="Search for help..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            autoFocus
          />
        </div>

        {searchQuery.length === 0 && (
          <button className="help-center-tour-button" onClick={() => {
            closeHelp();
            startTour();
          }}>
            <HelpCircle size={16} />
            Restart guided tour
          </button>
        )}

        <div className="help-center-content">
          {filteredSections.length === 0 ? (
            <div className="help-center-empty">
              <Search size={32} />
              <h3>No results found</h3>
              <p>Try a different search term</p>
            </div>
          ) : (
            filteredSections.map(section => (
              <section key={section.id} className="help-section">
                <h3 className="help-section-title">
                  <span>{section.icon}</span>
                  {section.title}
                </h3>
                <div className="help-faq-list">
                  {section.items.map((item, idx) => {
                    const itemId = `${section.id}-${idx}`;
                    const isExpanded = expandedItems.has(itemId);

                    return (
                      <div key={itemId} className="faq-item">
                        <button
                          className="faq-question"
                          onClick={() => toggleItem(itemId)}
                        >
                          <span>{item.q}</span>
                          <ChevronDown
                            size={18}
                            className={`faq-chevron ${isExpanded ? 'expanded' : ''}`}
                          />
                        </button>
                        {isExpanded && (
                          <div className="faq-answer">
                            {item.a}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </section>
            ))
          )}
        </div>

        <div className="help-center-footer">
          <p>Still need help? Check the documentation or contact your supervisor.</p>
        </div>
      </div>
    </div>
  );
};

export default HelpCenter;
